
import { PlaceHolderImages } from "./placeholder-images";

export type Project = {
  id: string;
  title: string;
  description: string;
  longDescription: string;
  technologies: string[];
  challenges: string;
  outcomes: string;
  imageUrl: string;
  imageHint: string;
  link: string;
  github: string;
};

export const projects: Project[] = [
  {
    id: "1",
    title: "Apex Dashboard",
    description: "High-performance analytics dashboard for real-time monitoring.",
    longDescription: "Apex Dashboard is a comprehensive data visualization tool built for enterprise scale. It allows teams to monitor key performance indicators in real-time with zero latency. The architecture utilizes WebSockets for live data feeds and a highly optimized React frontend.",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Recharts", "Node.js"],
    challenges: "Managing massive data streams without degrading UI performance and ensuring mobile responsiveness for complex charts.",
    outcomes: "Reduced page load time by 40% and improved data processing speed by 25%. Successfully handled over 10,000 concurrent metrics.",
    imageUrl: PlaceHolderImages.find(img => img.id === "project-1")?.imageUrl || "",
    imageHint: "dashboard ui",
    link: "#",
    github: "#"
  },
  {
    id: "2",
    title: "FitPulse Mobile",
    description: "A social fitness application that tracks workouts and health metrics.",
    longDescription: "FitPulse is a mobile-first application designed to help users track their fitness journey while connecting with a global community. It features advanced GPS tracking, personalized workout plans generated by AI, and social sharing capabilities.",
    technologies: ["React Native", "Firebase", "Redux", "Google Maps API"],
    challenges: "Implementing precise location tracking that is battery efficient and maintaining data consistency across multiple devices.",
    outcomes: "Reached 50,000 active monthly users within the first 6 months and maintained a 4.8 star rating on the App Store.",
    imageUrl: PlaceHolderImages.find(img => img.id === "project-2")?.imageUrl || "",
    imageHint: "mobile app interface",
    link: "#",
    github: "#"
  },
  {
    id: "3",
    title: "SmartHome Connect",
    description: "IoT platform for managing smart home devices from a single interface.",
    longDescription: "A sophisticated platform that integrates with various IoT protocols to provide a unified control panel for smart homes. Users can automate routines, monitor energy usage, and secure their premises remotely.",
    technologies: ["Go", "MQTT", "React", "PostgreSQL", "Docker"],
    challenges: "Securing the communication between devices and the central hub against potential intrusion while supporting legacy device protocols.",
    outcomes: "Implemented a zero-trust security model and achieved sub-100ms latency for device control commands.",
    imageUrl: PlaceHolderImages.find(img => img.id === "project-3")?.imageUrl || "",
    imageHint: "smart home tech",
    link: "#",
    github: "#"
  },
  {
    id: "4",
    title: "Artisan Marketplace",
    description: "A peer-to-peer e-commerce platform for digital and physical art.",
    longDescription: "Artisan is a marketplace dedicated to independent creators. It provides tools for inventory management, secure payments, and global shipping logistics, focusing on a minimalist and visually appealing shopping experience.",
    technologies: ["Next.js", "Stripe", "Supabase", "Framer Motion"],
    challenges: "Building a highly performant image delivery system for high-resolution artwork and ensuring a seamless checkout process.",
    outcomes: "Successfully processed over $1M in transactions in the first year and onboarded 2,000+ artists worldwide.",
    imageUrl: PlaceHolderImages.find(img => img.id === "project-4")?.imageUrl || "",
    imageHint: "art marketplace",
    link: "#",
    github: "#"
  }
];
